export const API_ENDPOINTS = {
  LOGIN: '/login',
  REGISTER: '/register',
  LOGOUT: '/logout',
  FORGET_PASSWORD: '/forget-password',
  CATEGORIES: '/sardarbaba-categories',
  // DIETARY: '/dietary.json',
  DIETARY: 'sardarbaba-brand',
  BRANDS: '/sardarbaba-brand',
  PRODUCTS: '/sardarbaba-products',
  PRODUCT: '/sardarbaba-products',
  // RELATED_PRODUCTS: '/related_products.json',
  // FLASH_SELL_PRODUCTS: '/sardarbaba-brand',
  // BEST_SELLER_PRODUCTS: '/sardarbaba-brand',
  // BEST_SELLER_GROCERY_PRODUCTS: '/sardarbaba-brand',
  // POPULAR_PRODUCTS: '/sardarbaba-brand',
  // COOKIES_PRODUCTS: '/sardarbaba-brand',
  // CHIPS_PRODUCTS: '/sardarbaba-brand',
  // POPCORN_JERKY_PRODUCTS: '/sardarbaba-brand',
  // FRESH_VEGETABLES_PRODUCTS: '/sardarbaba-brand',
  // SEARCH: '/sardarbaba-brand',
  // ORDERS: '/sardarbaba-brand',
  // ORDER: '/sardarbaba-brand',
  // ORDER_STATUS: '/sardarbaba-brand',
  // ADDRESS: '/sardarbaba-brand',
  // PAYMENT: '/sardarbaba-brand',
  // CONTACT: '/sardarbaba-brand',
  // SHOP: '/sardarbaba-brand',
  // SHOPS: '/sardarbaba-brand',
  // WISHLIST: '/sardarbaba-brand',

  RELATED_PRODUCTS: '/RELATED_PRODUCTS',
  FLASH_SELL_PRODUCTS: '/FLASH_SELL_PRODUCTS',
  BEST_SELLER_PRODUCTS: '/BEST_SELLER_PRODUCTS.',
  BEST_SELLER_GROCERY_PRODUCTS: '/BEST_SELLER_GROCERY_PRODUCTS',
  POPULAR_PRODUCTS: '/POPULAR_PRODUCTS',
  COOKIES_PRODUCTS: '/COOKIES_PRODUCTS',
  CHIPS_PRODUCTS: '/CHIPS_PRODUCTS',
  POPCORN_JERKY_PRODUCTS: '/POPCORN_JERKY_PRODUCTS',
  FRESH_VEGETABLES_PRODUCTS: '/FRESH_VEGETABLES_PRODUCTS',
  SEARCH: '/SEARCH.json',
  ORDERS: '/ORDERS',
  ORDER: '/ORDER',
  ORDER_STATUS: '/ORDER_STATUS',
  ADDRESS: '/ADDRESS',
  PAYMENT: '/PAYMENT',
  CONTACT: '/CONTACT',
  SHOP: '/SHOP',
  SHOPS: '/SHOPS',
  WISHLIST: '/WISHLIST',
};
