export const bundleData = [
  {
    id: 1,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/5.png',
    title: 'bundle-title-one',
    description: 'bundle-description',
  },
  {
    id: 2,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/6.png',
    title: 'bundle-title-two',
    description: 'bundle-description',
  },
  {
    id: 3,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/7.png',
    title: 'bundle-title-three',
    description: 'bundle-description',
  },
  {
    id: 4,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/8.png',
    title: 'bundle-title-four',
    description: 'bundle-description',
  },
  {
    id: 5,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/9.png',
    title: 'bundle-title-one',
    description: 'bundle-description',
  },
  {
    id: 6,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/10.png',
    title: 'bundle-title-two',
    description: 'bundle-description',
  },
  {
    id: 7,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/11.png',
    title: 'bundle-title-three',
    description: 'bundle-description',
  },
  {
    id: 8,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/12.png',
    title: 'bundle-title-four',
    description: 'bundle-description',
  },
  {
    id: 9,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/13.png',
    title: 'bundle-title-one',
    description: 'bundle-description',
  },
  {
    id: 10,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/14.png',
    title: 'bundle-title-two',
    description: 'bundle-description',
  },
  {
    id: 11,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/15.png',
    title: 'bundle-title-three',
    description: 'bundle-description',
  },
  {
    id: 12,
    slug: 'spring-cleaning-for-home-appliance',
    image: '/assets/images/bundle/16.png',
    title: 'bundle-title-four',
    description: 'bundle-description',
  },
];

export const bundleDataTwo = [
  {
    id: 1,
    slug: 'search',
    image: '/assets/images/card/school.png',
    title: 'School Stationary',
    description: 'We offer every kind of stationery.',
    bgColor: '#FFEED6',
  },
  {
    id: 2,
    slug: 'search',
    image: '/assets/images/card/university.png',
    title: 'Collage | University',
    description: 'We offer every kind of stationery.',
    bgColor: '#D9ECD2',
  },
  {
    id: 3,
    slug: 'search',
    image: '/assets/images/card/office.png',
    title: 'Office Stationary',
    description: 'We offer every kind of stationery.',
    bgColor: '#DBE5EF',
  },
  {
    id: 4,
    slug: 'search',
    image: '/assets/images/card/other.png',
    title: 'All Other',
    description: 'We offer every kind of stationery.',
    bgColor: '#EFD8D4',
  },
];
export const bundleDataThree = [
  {
    id: 1,
    slug: 'your-premium-tissue-paper-collection',
    image: '/assets/images/bundle/17.png',
    title: 'bundle-title-five',
  },
  {
    id: 2,
    slug: 'stay-strong-with-healthy-breakfast-everyday',
    image: '/assets/images/bundle/18.png',
    title: 'bundle-title-six',
  },
  {
    id: 3,
    slug: 'be-fit-and-healthy-with-diet-food-choice',
    image: '/assets/images/bundle/19.png',
    title: 'bundle-title-seven',
  },
];
